# version: '3'
services:
    laravel_app:
        container_name: 'laravel_app'
        build:
            context: .
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1000
        image: laravel_app
        # deploy:
        #     resources:
        #         limits:
        #             cpus: "1"
        #             memory: 2048M
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8000:80'
            - '5173:5173'
            # - '8080:8080'
        environment:
            WWWUSER: 1000
            LARAVEL_APP: 1
            XDEBUG_MODE: '${APP_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${APP_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        restart: unless-stopped
        volumes:
            - '.:/var/www/html'
        networks:
            - laravel_app_net
        depends_on:
            - laravel_app_pgsql
            - laravel_app_redis
            # - laravel_app_meilisearch

    laravel_app_pgsql:
        container_name: laravel_app_pgsql
        image: 'postgres:15'
        # deploy:
        #     resources:
        #         limits:
        #             cpus: '0.1'
        #             memory: '128M'
        restart: unless-stopped
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'laravel_app_pgsql:/var/lib/postgresql/data'
            - './vendor/laravel/app/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - laravel_app_net
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s

    laravel_app_redis:
        container_name: laravel_app_redis
        image: 'redis:alpine'
        # deploy:
        #     resources:
        #         limits:
        #             cpus: '0.1'
        #             memory: '128M'
        restart: unless-stopped
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'laravel_app_redis:/data'
        networks:
            - laravel_app_net
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    # laravel_app_meilisearch:
    #     container_name: laravel_app_meilisearch
    #     image: getmeili/meilisearch:v1.9.0
    #     # deploy:
    #     #     resources:
    #     #         limits:
    #     #             cpus: '0.1'
    #     #             memory: '128M'
    #     restart: unless-stopped
    #     ports:
    #         - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    #     environment:
    #         MEILI_ENV: '${MEILISEARCH_ENV:-production}'
    #         MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
    #         MEILI_MASTER_KEY: "X9vZVNkL1do9dTXPi4RovD-OWbHNXYAw-m-SZD__luU"
    #     volumes:
    #         - 'laravel_app_meilisearch:/meili_data'
    #     networks:
    #         - laravel_app_net
    #     healthcheck:
    #         test:
    #             - CMD
    #             - wget
    #             - '--no-verbose'
    #             - '--spider'
    #             - 'http://127.0.0.1:7700/health'
    #         retries: 3
    #         timeout: 5s

    # laravel_app_meilisearch_ui:
    #     container_name: laravel_app_meilisearch_ui
    #     image: riccoxie/meilisearch-ui:latest
    #     # deploy:
    #     #     resources:
    #     #         limits:
    #     #             cpus: '0.1'
    #     #             memory: '128M'
    #     restart: unless-stopped
    #     ports:
    #         - "8080:24900"
    #     environment:
    #         MEILISEARCH_URL: "http://laravel_app_meilisearch:7700"
    #     networks:
    #         - laravel_app_net
    #     depends_on:
    #         - laravel_app_meilisearch

networks:
    laravel_app_net:
        name: laravel_app_net
        driver: bridge
volumes:
    laravel_app_pgsql:
        driver: local
    laravel_app_redis:
        driver: local
    # laravel_app_meilisearch:
    #     driver: local
